isAutoDeployProducerVerticle: true 
configurations:
  - identifier: accesslog-for-es-and-axiom
    logPattern: "%D cs-uri %m %s %h %{User-Agent}i %{x-ip}i %B"
    appenders:
      - appenderClassName : com.romanpierson.vertx.web.accesslogger.appender.elasticsearch.impl.ElasticSearchAppender
        config:
          instanceIdentifier: axiom-accesslog
          fieldNames:
            - duration
            - uri
            - method
            - status
            - host
            - useragent
            - ip
            - bytes
      - appenderClassName : com.romanpierson.vertx.web.accesslogger.appender.elasticsearch.impl.ElasticSearchAppender
        config:
          instanceIdentifier: es-accesslog
          fieldNames:
            - duration
            - uri
            - method
            - status
            - host
            - useragent
            - ip
            - bytes